### ISSUE TITLE
Provide an Activity scope for @EBean

### ISSUE THREAD

**Issue by himamis** [androidannotations/androidannotations#1488]
Description: https://github.com/excilys/androidannotations/issues/205#issue-4756568.
As of now, beans needed in the Activity scope are created in the activity, and the passed down with constructors and setters to other beans and fragments.

**Comment by WonderCsabo** [comment]
Well, this was [rejected](https://github.com/excilys/androidannotations/issues/205#issuecomment-14354316) more than two years ago. Please note AA dependency injection is really limited. I am not sure we should try to improve it. Maybe we can try to provide better integration with Dagger or sg.

**Comment by himamis** [comment]
RoboGuice has ContextSingleton and FragmentSingleton annotations working similar as described above. I will do a test if they work with AA.

**Comment by WonderCsabo** [comment]
BTW, i am okay to accept contributions to implement this, for example this one is not that hard: https://github.com/excilys/androidannotations/issues/205#issue-4756568. But i do not have time to work on this solely myself.

**Comment by kenvanhoeylandt** [comment]
I think it would be better to have a more generic approach through a "Context" scope:

A bean with the scope`Scope.Context` is a bean that is bound to 1 specific context, like an `Activity`, an `Application` or a `Service`. When this bean is linked within other beans/fragments of this context, it will re-use the original bean of that context rather than instantiate a new bean.

I wrote some sample code at https://github.com/excilys/androidannotations/issues/1663

**Comment by gauravsak** [comment]
I think this issue is resolved as you can use @RootContext to access the activity in the bean. @WonderCsabo Please mark as closed. Thanks!

**Comment by WonderCsabo** [comment]
@gauravsak no, it was not resolved. This issue is not about accessing the root Context from the bean, it is about how the bean instances are created. Currently we always create a new instance for non-singleton beans, but this issue wants only one instance per Activity.

**Comment by smaugho** [comment]
Hi, I would like to implement this one, using the proposal on #2198 . Please @WonderCsabo , @dodgex  let me know if you agree with that solution.

**Comment by smaugho** [comment]
@WonderCsabo, I'm implementing this feature. I've added the BeanHolder interface to support the Activity scope. But doing it I realized that this can be right now extended to the Fragments, so we could have also the `@EBean` scope `Fragment`, specially since now we've added the support for `@RootFragment` on #2202 . 

Seems less useful, but seems trivial to add. A use case would be if you have several beans in a same fragment, and you want from several of them inject another which is the same instance for all of them. 

In fact, could be quite useful to implement "Routers (Navigators)".. Basically an @EBean which handles navigation, for whole a section. Typically I inject it, and since it is kind of Stateless I don't worry in creating several instances of it if needed. But adding the scope "Fragment" to it, would permit to inject a single instance for different Fragments in the same section (at least in this use case, it reduces the use of memory). 

Well, I will add it, and if you decide don't to keep it, so I move it only toward the `@EActivityHolder`.

**Comment by WonderCsabo** [comment]
@smaugho if it is simply to add, go for it!

**Comment by smaugho** [comment]
@WonderCsabo , in the scope "singleton", the factory method is created like this:

```java
public static TestModel_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new TestModel_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }
```

I don't understand the "OnViewChangedNotifier" that much, so I'm not sure if this would be needed for the Activity scope. 

Also, I don't get why the "init" is not called from within the constructor on this case, since the constructor is private. 

I'll not include the "OnViewChangedNotifier" now, but please let me know if required (a general explanation of those notifiers logic would help also). 

Thanks!

**Comment by WonderCsabo** [comment]
Unfortunately i do not really remember the exact workings of that class, it was created 5 years ago, before i joined the project. However i think it is needed. Please check how a non-singleton bean is created.

**Comment by smaugho** [comment]
In the case of a non-singleton, simply the private constructor is called. nothing related to OnViewChangedNotifier there.
